project:
  type: website
  output-dir: docs

# Meta
description-meta: "Copy adapted of Dr. Gang He Quarto Academic Website"
author-meta: "Juanjo Medina"

website:
  title: "juanjomedina.com"
  image: "https://quarto.org/quarto.png"
  description: "My Academid Website"
 
  navbar:
    background: light  # You can change the background color here

    left:   # You can comment out all navigation items here if you just like to keep the index page only
#      - text: Home
#        href: index.qmd
      - text: About
        menu:
          - text: News
            href: posts.qmd
          - text: Contact
            href: contact.qmd             
      - text: Research
        menu:
          - text: List of Publications
            href: publications.qmd
          - text: Recent projects
            href: projects.qmd                                
      - text: Teaching # Comment the Teaching part out to remove the Teaching page
        menu: 
          - text: Current teaching
            href: teaching.qmd 
          - text: Resources and Textbooks
            href: textbooks.qmd
      - text: Blog
        href: https://www.pensarlaseguridad.es
        target: _blank


    right: 
      - text: CV
        href: files/medina_cva.pdf
      - icon: github
        href: https://github.com/jjmedinaariza
        target: _blank
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app/profile/jjmedina.bsky.social
        target: _blank      
      - icon: rss
        href: posts.xml
        target: _blank
  
  page-navigation: true
  
  page-footer: 
    center: "Build on [Quart Academic Website Template](https://github.com/drganghe/quarto-academic-website-template) adapted by [Dr. Gang He](http://drganghe.github.io)"
    right:  
      - icon: github
        href: https://github.com/drganghe/quarto-academic-website-template
        target: _blank
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: unlinked
  
  repo-url: https://github.com/drganghe/quarto-academic-website-template
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://drganghe.github.io/quarto-academic-website-template"
  
  google-analytics:
    tracking-id: ""  # Please delete or replace with your own tracking ID
    anonymize-ip: true 

bibliography: references.bib  # Add references.bib to the root folder to enable the bibliography function

format:
  html:
    theme: 
      dark: darkly
      light: lux
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

